---
title: "EY58 Data Analysis"
author: "Emily Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
library(reshape2)
library(gridExtra)
library(ggplot2)

g <- read_excel("~/Documents/Experiments/EY58 Liq Nanoluc.xlsx", 
    sheet = "OD")
h <- read_excel("~/Documents/Experiments/EY58 Liq Nanoluc.xlsx", 
    sheet = "Lum")
```


```{r}
p <- ggplot(h, aes(x=Hours)) + 
  geom_point(aes(y = A1), color="steelblue", alpha = 0.5) + 
  geom_point(aes(y = A2), color="steelblue", alpha = 0.5) + 
  geom_point(aes(y = B1), color="steelblue", alpha = 0.5) +
  geom_point(aes(y = B2), color="steelblue", alpha = 0.5) + 
  geom_point(aes(y = C3), color="orange", alpha = 0.5) + 
  geom_point(aes(y = C4), color="orange", alpha = 0.5) + 
  geom_point(aes(y = D3), color="orange", alpha = 0.5) +
  geom_point(aes(y = D4), color="orange", alpha = 0.5) + 
  geom_point(aes(y = E1), color="pink", alpha = 0.5) + 
  geom_point(aes(y = E2), color="pink", alpha = 0.5) + 
  geom_point(aes(y = F1), color="pink", alpha = 0.5) +
  geom_point(aes(y = F2), color="pink", alpha = 0.5) 

p<- p +labs(title=" Nanoluc 4X ",
        x ="Time (hours)", y = "Luminescence (AU)")
p
#ggsave("4X Lum.png")
 
p1 <- ggplot(h, aes(x=Hours)) + 
  geom_point(aes(y = A5), color="steelblue", alpha = 0.5) + 
  geom_point(aes(y = A6), color="steelblue", alpha = 0.5) + 
  geom_point(aes(y = B5), color="steelblue", alpha = 0.5) +
  geom_point(aes(y = B6), color="steelblue", alpha = 0.5) +
  geom_point(aes(y = C7), color="orange", alpha = 0.5) + 
  geom_point(aes(y = C8), color="orange", alpha = 0.5) + 
  geom_point(aes(y = D7), color="orange", alpha = 0.5) +
  geom_point(aes(y = D8), color="orange", alpha = 0.5) + 
  geom_point(aes(y = E5), color="pink", alpha = 0.5) + 
  geom_point(aes(y = E6), color="pink", alpha = 0.5) + 
  geom_point(aes(y = F5), color="pink", alpha = 0.5) +
  geom_point(aes(y = F6), color="pink", alpha = 0.5) 
p1<- p1 +labs(title=" Nanoluc 1X ",
        x ="Time (hours)", y = "Luminescence (AU)")

p1
#ggsave("1X Lum.png")
p2 <- ggplot(h, aes(x=Hours)) + 
  geom_point(aes(y = A9), color="steelblue", alpha = 0.5) + 
  geom_point(aes(y = A10), color="steelblue", alpha = 0.5) + 
  geom_point(aes(y = B9), color="steelblue", alpha = 0.5) +
  geom_point(aes(y = B10), color="steelblue", alpha = 0.5) +
  geom_point(aes(y = C11), color="orange", alpha = 0.5) + 
  geom_point(aes(y = C12), color="orange", alpha = 0.5) + 
  geom_point(aes(y = D11), color="orange", alpha = 0.5) +
  geom_point(aes(y = D12), color="orange", alpha = 0.5) +
  geom_point(aes(y = E9), color="pink", alpha = 0.5) + 
  geom_point(aes(y = E10), color="pink", alpha = 0.5) + 
  geom_point(aes(y = F9), color="pink", alpha = 0.5) +
  geom_point(aes(y = F10), color="pink", alpha = 0.5) 

p2<- p2 +labs(title=" Nanoluc 0.25X ",
        x ="Time (hours)", y = "Luminescence (AU)")

p2
#ggsave("0.25X Lum.png")
```

```{r}
q <- ggplot(g, aes(x=Hours)) + 
  geom_point(aes(y = A1), color="steelblue", alpha = 0.5) + 
  geom_point(aes(y = A2), color="steelblue", alpha = 0.5) + 
  geom_point(aes(y = B1), color="steelblue", alpha = 0.5) +
  geom_point(aes(y = B2), color="steelblue", alpha = 0.5) + 
  geom_point(aes(y = C3), color="orange", alpha = 0.5) + 
  geom_point(aes(y = C4), color="orange", alpha = 0.5) + 
  geom_point(aes(y = D3), color="orange", alpha = 0.5) +
  geom_point(aes(y = D4), color="orange", alpha = 0.5) + 
  geom_point(aes(y = E1), color="pink", alpha = 0.5) + 
  geom_point(aes(y = E2), color="pink", alpha = 0.5) + 
  geom_point(aes(y = F1), color="pink", alpha = 0.5) +
  geom_point(aes(y = F2), color="pink", alpha = 0.5) 

q<- q +labs(title=" Nanoluc 4X ",
        x ="Time (hours)", y = "OD")
q
#ggsave("4X OD.png")
 
q1 <- ggplot(g, aes(x=Hours)) + 
  geom_point(aes(y = A5), color="steelblue", alpha = 0.5) + 
  geom_point(aes(y = A6), color="steelblue", alpha = 0.5) + 
  geom_point(aes(y = B5), color="steelblue", alpha = 0.5) +
  geom_point(aes(y = B6), color="steelblue", alpha = 0.5) +
  geom_point(aes(y = C7), color="orange", alpha = 0.5) + 
  geom_point(aes(y = C8), color="orange", alpha = 0.5) + 
  geom_point(aes(y = D7), color="orange", alpha = 0.5) +
  geom_point(aes(y = D8), color="orange", alpha = 0.5) + 
  geom_point(aes(y = E5), color="pink", alpha = 0.5) + 
  geom_point(aes(y = E6), color="pink", alpha = 0.5) + 
  geom_point(aes(y = F5), color="pink", alpha = 0.5) +
  geom_point(aes(y = F6), color="pink", alpha = 0.5) 
q1<- q1 +labs(title=" Nanoluc 1X ",
        x ="Time (hours)", y = "OD")

q1
#ggsave("1X OD.png")

q2 <- ggplot(g, aes(x=Hours)) + 
  geom_point(aes(y = A9), color="steelblue", alpha = 0.5) + 
  geom_point(aes(y = A10), color="steelblue", alpha = 0.5) + 
  geom_point(aes(y = B9), color="steelblue", alpha = 0.5) +
  geom_point(aes(y = B10), color="steelblue", alpha = 0.5) +
  geom_point(aes(y = C11), color="orange", alpha = 0.5) + 
  geom_point(aes(y = C12), color="orange", alpha = 0.5) + 
  geom_point(aes(y = D11), color="orange", alpha = 0.5) +
  geom_point(aes(y = D12), color="orange", alpha = 0.5) +
  geom_point(aes(y = E9), color="pink", alpha = 0.5) + 
  geom_point(aes(y = E10), color="pink", alpha = 0.5) + 
  geom_point(aes(y = F9), color="pink", alpha = 0.5) +
  geom_point(aes(y = F10), color="pink", alpha = 0.5) 

q2<- q2 +labs(title=" Nanoluc 0.25X",
        x ="Time (hours)", y = "OD")

q2
#ggsave("0.25X OD.png")
```

```{r}

r<- ggplot()+ 
  geom_point(data = data.frame(x = g$A1, y = h$A1), aes(x = x, y = y), color="steelblue", alpha = 0.5)+
   geom_point(data = data.frame(x = g$A2, y = h$A2), aes(x = x, y = y), color="steelblue", alpha = 0.5)+
  geom_point(data = data.frame(x = g$B1, y = h$B1), aes(x = x, y = y), color="steelblue", alpha = 0.5)+
   geom_point(data = data.frame(x = g$B2, y = h$B2), aes(x = x, y = y), color="steelblue", alpha = 0.5)+
  geom_point(data = data.frame(x = g$C3, y = h$C3), aes(x = x, y = y), color="steelblue", alpha = 0.5)+
   geom_point(data = data.frame(x = g$C4, y = h$C4), aes(x = x, y = y), color="steelblue", alpha = 0.5)+
  geom_point(data = data.frame(x = g$D3, y = h$D3), aes(x = x, y = y), color="steelblue", alpha = 0.5)+
   geom_point(data = data.frame(x = g$D4, y = h$D4), aes(x = x, y = y), color="steelblue", alpha = 0.5)+
   geom_point(data = data.frame(x = g$E1, y = h$E1), aes(x = x, y = y), color="steelblue", alpha = 0.5)+
   geom_point(data = data.frame(x = g$E2, y = h$E2), aes(x = x, y = y), color="steelblue", alpha = 0.5)+
  geom_point(data = data.frame(x = g$F1, y = h$F1), aes(x = x, y = y), color="steelblue", alpha = 0.5)+
   geom_point(data = data.frame(x = g$F2, y = h$F2), aes(x = x, y = y), color="steelblue", alpha = 0.5)
r<- r +labs(title=" Nanoluc OD 1",
        x ="OD", y = "Luminescence")
r
#ggsave("OD1.png")
r1<- ggplot()+
  geom_point(data = data.frame(x = g$A5, y = h$A5), aes(x = x, y = y), color="orange", alpha = 0.5)+
   geom_point(data = data.frame(x = g$A6, y = h$A6), aes(x = x, y = y), color="orange", alpha = 0.5)+
  geom_point(data = data.frame(x = g$B5, y = h$B5), aes(x = x, y = y), color="orange", alpha = 0.5)+
   geom_point(data = data.frame(x = g$B6, y = h$B6), aes(x = x, y = y), color="orange", alpha = 0.5)+
  geom_point(data = data.frame(x = g$C7, y = h$C7), aes(x = x, y = y), color="orange", alpha = 0.5)+
   geom_point(data = data.frame(x = g$C8, y = h$C8), aes(x = x, y = y), color="orange", alpha = 0.5)+
  geom_point(data = data.frame(x = g$D7, y = h$D7), aes(x = x, y = y), color="orange", alpha = 0.5)+
   geom_point(data = data.frame(x = g$D8, y = h$D8), aes(x = x, y = y), color="orange", alpha = 0.5)+
  geom_point(data = data.frame(x = g$E5, y = h$E5), aes(x = x, y = y),
color="orange", alpha = 0.5)+
   geom_point(data = data.frame(x = g$E6, y = h$E6), aes(x = x, y = y), color="orange", alpha = 0.5)+
  geom_point(data = data.frame(x = g$F5, y = h$F5), aes(x = x, y = y), color="orange", alpha = 0.5)+
   geom_point(data = data.frame(x = g$F6, y = h$F6), aes(x = x, y = y), color="orange", alpha = 0.5)
r1<- r1 +labs(title=" Nanoluc OD 0.1",
        x ="OD", y = "Luminescence")
r1
#ggsave("OD 0.1.png")
r2<- ggplot()+
  geom_point(data = data.frame(x = g$A9, y = h$A9), aes(x = x, y = y), color="pink", alpha = 0.5)+
   geom_point(data = data.frame(x = g$A10, y = h$A10), aes(x = x, y = y), color="pink", alpha = 0.5)+
  geom_point(data = data.frame(x = g$B9, y = h$B9), aes(x = x, y = y), color="pink", alpha = 0.5)+
   geom_point(data = data.frame(x = g$B10, y = h$B10), aes(x = x, y = y), color="pink", alpha = 0.5)+
  geom_point(data = data.frame(x = g$C11, y = h$C11), aes(x = x, y = y), color="pink", alpha = 0.5)+
   geom_point(data = data.frame(x = g$C12, y = h$C12), aes(x = x, y = y), color="pink", alpha = 0.5)+
  geom_point(data = data.frame(x = g$D11, y = h$D11), aes(x = x, y = y), color="pink", alpha = 0.5)+
   geom_point(data = data.frame(x = g$D12, y = h$D12), aes(x = x, y = y), color="pink", alpha = 0.5)+
  geom_point(data = data.frame(x = g$E9, y = h$E9), aes(x = x, y = y), color="pink", alpha = 0.5)+
   geom_point(data = data.frame(x = g$E10, y = h$E10), aes(x = x, y = y), color="pink", alpha = 0.5)+
  geom_point(data = data.frame(x = g$F9, y = h$F9), aes(x = x, y = y), color="pink", alpha = 0.5)+
   geom_point(data = data.frame(x = g$F10, y = h$F10), aes(x = x, y = y), color="pink", alpha = 0.5)
r2<- r2 +labs(title=" Nanoluc OD 0.01",
        x ="OD", y = "Luminescence")

r2
#ggsave("OD 0.01.png")
```
